
format = """
[](#f4b8e4)\
$python\
$username\
[](bg:#313244 fg:#f4b8e4)\
$directory\
[](fg:#313244 bg:#45475a)\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#45475a bg:#45475a)\
$docker_context\
[](fg:#45475a bg:#BD93F9)\
$time\
[ ](fg:#BD93F9)
"""

command_timeout = 5000

[username]
show_always = true
style_user = "bg:#f4b8e4 fg:#1e1e2e"
style_root = "bg:#f38ba8 fg:#1e1e2e"
format = '[$user ]($style)'

[directory]
style = "bg:#313244 fg:#cdd6f4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#45475a fg:#BD93F9"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#45475a fg:#cdd6f4"
format = '[$all_status$ahead_behind ]($style)'

[python]
style = "bg:#1e1e2e fg:#cdd6f4"
format = '[(\($virtualenv\) )]($style)'

[c]
symbol = " "
style = "bg:#f4b8e4 fg:#1e1e2e"
format = '[ $symbol ($version)]($style)'

[elixir]
symbol = " "
style = "bg:#f4b8e4 fg:#1e1e2e"
format = '[ $symbol ($version)]($style)'

[elm]
symbol = " "
style = "bg:#f4b8e4 fg:#1e1e2e"
format = '[ $symbol ($version)]($style)'

[golang]
symbol = " "
style = "bg:#f4b8e4 fg:#1e1e2e"
format = '[ $symbol ($version)]($style)'

[haskell]
symbol = " "
style = "bg:#f4b8e4 fg:#1e1e2e"
format = '[ $symbol ($version)]($style)'

[java]
symbol = " "
style = "bg:#fab387 fg:#1e1e2e"
format = '[ $symbol ($version)]($style)'

[julia]
symbol = " "
style = "bg:#f4b8e4 fg:#1e1e2e"
format = '[ $symbol ($version)]($style)'

[nodejs]
symbol = ""
style = "bg:#f4b8e4 fg:#1e1e2e"
format = '[ $symbol ($version)]($style)'

[nim]
symbol = " "
style = "bg:#f4b8e4 fg:#1e1e2e"
format = '[ $symbol ($version)]($style)'

[rust]
symbol = ""
style = "bg:#f4b8e4 fg:#1e1e2e"
format = '[ $symbol ($version)]($style)'

[docker_context]
symbol = " "
style = "bg:#94e2d5 fg:#1e1e2e"
format = '[ $symbol $context ]($style)$path'

[time]
disabled = false
time_format = "%R"
style = "bg:#BD93F9 fg:#1e1e2e"
format = '[ $time ]($style)'
